import Head from 'next/head'
import Footer from "@/components/Footer";
import HeaderInner from "@/components/HeaderInner";

import styles from "../styles/Main.module.scss"
import classNames from 'classnames/bind'

const cx = classNames.bind(styles);

export default function InnerLayout({ children }) {
    return (
        <>
            <Head>
                <title>RNMSO</title>
                <meta charSet="utf-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                <meta name="description" content="Generated by create next app" />
            </Head>
            <HeaderInner />
            <main className={cx("page-content")}>
                {children}
            </main>
            <Footer />
        </>
    )
}