import Head from 'next/head';
import Footer from '@/components/Footer';
import Header from '@/components/Header';

export function MainLayout({ children }) {
  return (
    <>
      <Head>
        <title>RNMSO</title>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <main>{children}</main>
      <Footer />
    </>
  );
}
